### ISSUE TITLE
Cannot parse response (again)

### ISSUE THREAD

**Issue by bestouff** [fagga/transmission-remote-cli#164]
Hi,

On a debian system, using transmission-cli 2.84-3 and transmission-remote-cli 21.7.0-1 I have this error:
`Cannot parse response: {"arguments":{"torrents":[{"addedDate":1425250211,"bandwidthPriority":0,"desiredAvailable":0,"downloadDir":"/common/crash/films","downloadLimit":500,"downloadLimited":false,"errorString":"","eta":-2,"haveUnchecked":0,"haveValid":2389083100,"id":1,"isPrivate":true,"name": ` etc.

On potential problem is that the (loong) line ends with: `scrapeState":1,"seederCount":0,"tier":1}],"uploadLimit":200,"uploadLimited":false,"uploadRatio":2.0000,"uploadedEver":1466502396},`
Yes, it looks like it's not really finished. May a buffer is too small somewhere, which makes the response truncated ?

**Comment by bestouff** [comment]
It looks more and more like a too small buffer: the length of the (truncated) response is just 4096 chars.
So probably somewhere in urllib2 there's a 4096 bytes buffer which needs to be bigger (I've never touched python so it's just a wild guess).

**Comment by fagga** [comment]
Thanks for hunting that bug down.
The latest commit should fix it.

**Comment by bestouff** [comment]
It still doesn't. The response fails after >64k.
I tried with this code:
```python
        response = b''
        while True:
            chunk = self.open_request.read(256)
            if not chunk:
                break
            print "got chunk: '" + chunk + "'\n"
            response += chunk
```
The last chunk looks like `got chunk: 'wnloadCount":-1,"hasAnnounced":true,"hasScraped":true,"host":"udp://open.demonii.com:133'` which is <256 and doesn't terminate properly the json data.

With your code, `transmission-remote-cli  2>&1 | wc -c` outputs 67440.

**Comment by fagga** [comment]
I've had the same issue a couple of times years ago, but it was always a one
time thing. It crashed at some random point but everything worked fine when I
tried again. But for you it seems to be consistent?

Try this:

```python
        debug('Expected response length: %s\n' % str(self.open_request.headers['content-length']))
        response = b''
        while True:
            chunk = self.open_request.read()
            if not chunk:
                break
            response += chunk
        debug('Response length: %s\n\n' % len(response))
```

Then start with the --debug option and look at the file debug.log.

Although I really don't know what to do with the results. No idea where that
bug could possibly lurk.

**Comment by bestouff** [comment]
Effectively there's a problem here:
```
Expected response length: 1600
Response length: 1600

Expected response length: 664034
Response length: 67416
```

**Comment by fagga** [comment]
Weird. Does this work?

```python
        response_length = int(self.open_request.headers['content-length'])
        response = b''
        while len(response) < response_length:
            response += self.open_request.read()
```

**Comment by bestouff** [comment]
... for now it still runs. I think it's blocked fetching the response, but I don't know for sure.

**Comment by fagga** [comment]
That means it's running in an endless loop. read() keeps reading but returns
an empty string (which means EOF) before the full response was read.

**Comment by bestouff** [comment]
Yep. Still blocked today.
Strange, because the GTK gui works well, and I guess it uses the same
mechanism.
